name: Update data
on:
  schedule:
    - cron: '15 6 * * *'   # daily 06:15 UTC
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt
      - name: Refresh data
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BING_API_KEY: ${{ secrets.BING_API_KEY }}
        run: |
          python scripts/crawler.py --refresh --summarise --weekly || true
          python scripts/build_site.py
      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "data: refresh" || echo "No changes"
          git push
